image: carterjones/manjaro


include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run job1 in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == "master"'                # Run job1 in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run job1 in pipelines for tags

test:
  only:
     - master
     - dev
     - develop
  stage: test
  before_script: 
     #installing dependencies 
     - sudo pacman -Syu --noconfirm && sudo pacman --noconfirm -S clang make cmake
     #pulling submodule 
     - git submodule update --init --recursive
     - mkdir build
     - cd build
     #pulling cxxopts from its repos and installing it. 
     - git pull https://github.com/jarro2783/cxxopts
     #as it is header only, just copy header lol.
     - cp cxxopts/include/cxxopts.hpp /usr/include/
     - cmake ..
     - make 
  script: 
     - make test
