image: carterjones/manjaro


include:
    - template: Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run job1 in merge request pipelines
    - if: '$CI_COMMIT_BRANCH == "master"'                # Run job1 in pipelines on the master branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_TAG'                               # Run job1 in pipelines for tags

test:
  only:
     - master
     - dev
     - develop
  stage: test
  before_script: 
     - sudo pacman -Syu --noconfirm && sudo pacman --noconfirm -S clang make cmake
     - git submodule update --init --recursive
     - mkdir build
     - cd build
     - cmake ..
     - make 
  script: 
     - make test
